Print help for category with no default framework
If you execute:
* $ umake
usage: umake [--help] [-v] [-r] {web,go,games,android,dart,ide} ...

Deploy and setup developers environment easily on ubuntu

positional arguments:
  {web,go,games,android,dart,ide}
                        Developer environment
    web                 Web Developer Environment
    go                  Go language
    games               Games Development Environment
    android             Android Development Environment
    dart                Dartlang Development Environment
    ide                 Generic IDEs

optional arguments:
  --help                Show this help
  -v, --verbose         Increase output verbosity (2 levels)
  -r, --remove          Remove specified framework if installed

Note that you can also configure different debug logs behaviors using LOG_CFG
pointing to a log yaml profile.

* Then:
$ umake web
ERROR: A default framework for category Web was requested where there is none

Which was cryptic to the user and they won't use "umake web --help".
Consequently, have umake web should this help automatically as web doesn't have
any default framework.

* Now:
$ umake web
ERROR: A default framework for category Web was requested where there is none
usage: umake web [-h] {firefox-dev} ...